"""DIMER pipeline for NAFNet-GoPro-width32 image deblurring (megvii-research/NAFNet).

Importing the package imports numpy and Pillow only; torch and safetensors are imported inside the functions that
need them, so validation and refusals never load a model library.
"""

from .metrics import (
    METRIC_DEFINITIONS,
    classical_outputs,
    gradient_energy,
    paired_difference,
    psnr,
    score,
    ssim,
    tune_unsharp,
    tune_wiener,
    unsharp_mask,
    wiener_deconvolve,
)
from .pipeline import (
    ARCH_CONFIG,
    ARTIFACT_FORMAT,
    CHECKPOINT_BYTES,
    CHECKPOINT_FILE,
    CHECKPOINT_MIRRORS,
    CHECKPOINT_SHA256,
    MANIFEST_NAME,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    MODEL_VARIANT,
    PARAMETER_COUNT,
    TRAINABLE_SCOPES,
    UPSTREAM_ARCH_SHA256,
    DeblurPipeline,
    convert_checkpoint,
    fetch_checkpoint,
    load_architecture,
    load_manifest,
    verify_checkpoint,
)
from .samples import (
    INPUT_SCHEMA,
    MAX_SIDE,
    MIN_PAIRS,
    MIN_SIDE,
    SAMPLE_IMAGES,
    build_new_data,
    build_sample_dataset,
    dataset_manifest,
    degrade,
    motion_kernel,
    read_byod,
    split_by_source,
    validate_records,
)

__all__ = [
    "ARCH_CONFIG",
    "ARTIFACT_FORMAT",
    "CHECKPOINT_BYTES",
    "CHECKPOINT_FILE",
    "CHECKPOINT_MIRRORS",
    "CHECKPOINT_SHA256",
    "INPUT_SCHEMA",
    "MANIFEST_NAME",
    "MAX_SIDE",
    "METRIC_DEFINITIONS",
    "MIN_PAIRS",
    "MIN_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "MODEL_VARIANT",
    "PARAMETER_COUNT",
    "SAMPLE_IMAGES",
    "TRAINABLE_SCOPES",
    "UPSTREAM_ARCH_SHA256",
    "DeblurPipeline",
    "build_new_data",
    "build_sample_dataset",
    "classical_outputs",
    "convert_checkpoint",
    "dataset_manifest",
    "degrade",
    "fetch_checkpoint",
    "gradient_energy",
    "load_architecture",
    "load_manifest",
    "motion_kernel",
    "paired_difference",
    "psnr",
    "read_byod",
    "score",
    "split_by_source",
    "ssim",
    "tune_unsharp",
    "tune_wiener",
    "unsharp_mask",
    "validate_records",
    "verify_checkpoint",
    "wiener_deconvolve",
]
